version: "3"

services:

  sensu-client:
    image: $REGISTRY_URL/sensu-client:dev
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/sensu-client/plugins:/etc/sensu/plugins
    privileged: true
    environment:
    - SENSU_HOST
    - SENSU_USER
    - SENSU_PASSWORD
    - CLIENT_NAME
    - CLIENT_IP