version: "3"

services:

  sensu-server:
    image: $REGISTRY_URL/sensu-server:dev
    volumes:
    - $PWD/sensu-server/config/check-docker.json:/etc/sensu/conf.d/check-docker.json
    - $PWD/sensu-server/checks/check-disk-usage.json:/etc/sensu/conf.d/check-disk-usage.json
    ports:
    - 4567:4567  # API PORT
    - 5672:5672  # rabbitmq
    - 15672:15672  # rabbitmq console
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"

  uchiwa:
    image: uchiwa/uchiwa
    volumes:
    - $PWD/sensu-server/config/uchiwa.json:/config/config.json
    depends_on:
    - sensu-server
    ports:
    - 3000:3000  # WEB UI PORT (uchiwa)
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"